### PR TITLE
Refactor CI workflow and add installation of build dependencies

### PR DESCRIPTION
**Pull request by sogartar**
Move build out-of-source to avoid implicit dependency on in-source building.
Put CI setup/building commands in scripts, so that they can be used also on developer machines.

### CODE REVIEW

**Comment by sogartar** [comment]
I am not sure that having these small scripts is useful now, but I wanted to avoid ending up with a fat github CI workflow script in the future.

**Comment by sogartar** [comment]
This is ready for review.

**Comment by sogartar** [comment]
@yzhang93 or @raikonenfnu could make a review?

**Review by powderluv — APPROVED** [review]
Can we please move all setup scripts to ci_setup/ or something like that? Don't want it to be used for regular developer builds. Feel free to merge and do in a follow on

**Comment by powderluv** [comment]
Lgtm

**Pull request merged**
